# Generated by Django 4.2.6 on 2023-10-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invited_code',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
    ]
