# Generated by Django 4.2.6 on 2023-11-19 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_organization_invited_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 17, 51, 50, 863637, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
