# Generated by Django 4.2.6 on 2023-10-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedbackmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50),
        ),
    ]
