# Generated by Django 4.2.6 on 2023-10-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedbackmodel_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='massage',
            new_name='message',
        ),
    ]
