# Generated by Django 4.2.6 on 2023-10-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_feedbackmodel_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='org_position',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
