# Generated by Django 4.2.6 on 2023-10-28 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_organization_invited_code'),
        ('feedback', '0007_feedbackmodel_org_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
